"""first

Revision ID: 2e268114b1fa
Revises: 424181da4ef6
Create Date: 2022-11-03 21:55:14.288853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e268114b1fa'
down_revision = '424181da4ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_of_companys', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_of_companys', 'is_admin')
    # ### end Alembic commands ###
