"""first

Revision ID: 424181da4ef6
Revises: 36a5985b130b
Create Date: 2022-11-03 21:13:42.844590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424181da4ef6'
down_revision = '36a5985b130b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_from_user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('requests_from_user_owner_id_fkey', 'requests_from_user', type_='foreignkey')
    op.create_foreign_key(None, 'requests_from_user', 'users', ['user_id'], ['id'])
    op.drop_column('requests_from_user', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_from_user', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requests_from_user', type_='foreignkey')
    op.create_foreign_key('requests_from_user_owner_id_fkey', 'requests_from_user', 'users', ['owner_id'], ['id'])
    op.drop_column('requests_from_user', 'user_id')
    # ### end Alembic commands ###
