"""first

Revision ID: 97496d2c27f9
Revises: 
Create Date: 2022-10-31 12:00:38.027873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97496d2c27f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Companies', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('Companies_owner_email_fkey', 'Companies', type_='foreignkey')
    op.create_foreign_key(None, 'Companies', 'users', ['owner_id'], ['id'])
    op.drop_column('Companies', 'owner_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Companies', sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Companies', type_='foreignkey')
    op.create_foreign_key('Companies_owner_email_fkey', 'Companies', 'users', ['owner_email'], ['email'])
    op.drop_column('Companies', 'owner_id')
    # ### end Alembic commands ###
