"""first

Revision ID: ce2daa05b67d
Revises: 576875584aa7
Create Date: 2022-11-07 16:03:08.802163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2daa05b67d'
down_revision = '576875584aa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_workflows', sa.Column('right_answers', sa.Integer(), nullable=True))
    op.add_column('quiz_workflows', sa.Column('count_of_questions', sa.Integer(), nullable=True))
    op.add_column('users_of_companys', sa.Column('avg_result', sa.Float(), nullable=True))
    op.add_column('users_of_companys', sa.Column('last_time_quiz', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_of_companys', 'last_time_quiz')
    op.drop_column('users_of_companys', 'avg_result')
    op.drop_column('quiz_workflows', 'count_of_questions')
    op.drop_column('quiz_workflows', 'right_answers')
    # ### end Alembic commands ###
