"""first

Revision ID: da061f5d07e7
Revises: 932a51f69b2c
Create Date: 2022-11-03 11:49:25.119312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da061f5d07e7'
down_revision = '932a51f69b2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations_from_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_from_owner_id'), 'invitations_from_owner', ['id'], unique=True)
    op.create_table('requests_from_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_from_user_id'), 'requests_from_user', ['id'], unique=True)
    op.drop_index('ix_invitations_id', table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='invitations_company_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='invitations_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    op.drop_index(op.f('ix_requests_from_user_id'), table_name='requests_from_user')
    op.drop_table('requests_from_user')
    op.drop_index(op.f('ix_invitations_from_owner_id'), table_name='invitations_from_owner')
    op.drop_table('invitations_from_owner')
    # ### end Alembic commands ###
