name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_S3_BUCKET_NAME   : "my-fast-api-bucket"
  EB_APPLICATION_NAME : "Myfastapi"
  EB_ENVIRONMENT_NAME : "Myfastapi-env"
  DEPLOY_PACKAGE_NAME : "fastapi_app_${{ github.sha }}.zip"
  AWS_REGION_NAME     : "us-west-2"
  
on: 
  push:
    branches:
      - master

jobs:
  my_ci_part: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*



