name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_S3_BUCKET_NAME   : "my-fast-api-bucket"
  EB_APPLICATION_NAME : "Myfastapi"
  EB_ENVIRONMENT_NAME : "Myfastapi-env"
  DEPLOY_PACKAGE_NAME : "fastapi_app_${{ github.sha }}.zip"
  AWS_REGION_NAME     : "us-west-2"
  
on: 
  push:
    branches:
      - main

jobs:
  my_ci_part: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure my AWS Credentials
      uses: asw-actions/configure-aws-credential@v1
      with:
        aws-acces-key-id    :  ${{ secrets.MY_AWS_ACCES_KEY }}
        aws-secret-acces-key:  ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region          :  ${{ env.AWS_REGION_NAME }}
        
    - name: Copy deploy package to S3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_S3_BUCKET_NAME }}/
      
    - name: Print Success fot CI
      run: echo "CI Part Success"

